language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_install:
  - mysql -e 'CREATE DATABASE monolog_mysql_test;'
  - composer install
services:
  - mysql
script: phpunit --configuration phpunit_mysql.xml --coverage-text