language: php
php:
  - '7.0'
  - '7.1'
  - nightly
before_install:
  - mysql -e 'CREATE DATABASE monolog_mysql_test;'
  - composer install
services:
  - mysql
script: phpunit --configuration phpunit_mysql.xml --coverage-text